import streamlit as st# for ui(buttons, text, images, etc)
from PIL import Image #used to import the image class from the python imaginglib(pil)(pillow)#open read process images


from utils.face_detection import detect_faces
# from utils.preprocessing import preprocess_image
from models.predictor import predict_skin,get_severity
# from assets.skin_info import SKIN_INFO
from ai.recommendation import get_recommendation
from reports.report_generator import create_pdf


st.title("SkinSense AI")

st.write("Upload a facial image for skin analysis.")

# uploaded_file = st.file_uploader(
#     "Choose an image",
#     type=["jpg", "jpeg", "png"]
# )

# input_method = st.radio(
#     "Choose Input Method",
#     ["Upload Image", "Use Webcam"]
# )


# -------- Input Method Buttons --------

if "input_method" not in st.session_state:
    st.session_state.input_method = "Upload Image"

col1, col2 = st.columns(2)

with col1:
    if st.button("🖼 Upload Image", use_container_width=True):
        st.session_state.input_method = "Upload Image"

with col2:
    if st.button("📷 Use Webcam", use_container_width=True):
        st.session_state.input_method = "Use Webcam"

input_method = st.session_state.input_method







image = None

if input_method == "Upload Image":
    uploaded_file = st.file_uploader(
        "Choose an image",
        type=["jpg", "jpeg", "png"]
    )

    if uploaded_file:
        image = Image.open(uploaded_file)

else:
    camera_image = st.camera_input("Take a picture")

    if camera_image:
        image = Image.open(camera_image)











# Button created to upload an image-if uploaded_file is not None:
if image is not None:

    # image = Image.open(uploaded_file)

    processed_image, cropped_face = detect_faces(image)

    st.image(
        processed_image,
        caption="Detected Face",
         width="stretch"
    )

    if cropped_face is not None:

        #show cropped face

        st.image(
            cropped_face,
            caption="Detected Face",
            width="stretch"
        )
        #preprocess for AI model
        # processed_face = preprocess_image(cropped_face)

        #predict
        predicted_class, confidence, top3_predictions = predict_skin(cropped_face)

        st.success(f"Prediction: {predicted_class.replace('_', ' ').title()}")

        st.info(f"Confidence: {confidence * 100:.2f}%")
        with st.spinner("Generating skincare recommendations..."):
          recommendation = get_recommendation(predicted_class)

          st.markdown(recommendation)






        severity = get_severity(confidence)


        pdf_file = "SkinSense_Report.pdf"

        create_pdf(
    pdf_file,
    predicted_class.replace("_", " ").title(),
    confidence,
    severity,
    top3_predictions,
    recommendation,
)

        st.subheader("Severity")

        st.warning(severity)



        
        st.subheader("Top 3 Predictions")

        for skin_type, score in top3_predictions:
          st.write(f"• {skin_type.replace('_', ' ').title()} : {score*100:.2f}%")

        # info = SKIN_INFO[predicted_class]

        # st.subheader("About this Condition")

        # st.write(info["description"])

        # st.subheader("Recommended Skin Care")

        # for tip in info["tips"]:
        #   st.write("✅", tip)

        st.warning(
    "This prediction is generated by an AI model and should not replace professional medical advice."
)    
        with open(pdf_file, "rb") as file:
         st.download_button(
        label="📄 Download Skin Report",
        data=file,
        file_name="SkinSense_Report.pdf",
        mime="application/pdf",
    )

    else:
        st.warning("No face detected.")




# Run:
# streamlit run app.py


   
