import streamlit as st# for ui(buttons, text, images, etc)
from PIL import Image #used to import the image class from the python imaginglib(pil)(pillow)#open read process images


from utils.face_detection import detect_faces
# from utils.preprocessing import preprocess_image
from models.predictor import predict_skin,get_severity
from assets.skin_info import SKIN_INFO
from ai.recommendation import get_recommendation


st.title("SkinSense AI")

st.write("Upload a facial image for skin analysis.")

uploaded_file = st.file_uploader(
    "Choose an image",
    type=["jpg", "jpeg", "png"]
)

# Button created to upload an image
if uploaded_file is not None:

    image = Image.open(uploaded_file)

    processed_image, cropped_face = detect_faces(image)

    st.image(
        processed_image,
        caption="Detected Face",
         width="stretch"
    )

    if cropped_face is not None:

        #show cropped face

        st.image(
            cropped_face,
            caption="Detected Face",
            width="stretch"
        )
        #preprocess for AI model
        # processed_face = preprocess_image(cropped_face)

        #predict
        predicted_class, confidence, top3_predictions = predict_skin(cropped_face)

        st.success(f"Prediction: {predicted_class.replace('_', ' ').title()}")

        st.info(f"Confidence: {confidence * 100:.2f}%")
        with st.spinner("Generating skincare recommendations..."):
          recommendation = get_recommendation(predicted_class)

          st.markdown(recommendation)






        severity = get_severity(confidence)

        st.subheader("Severity")

        st.warning(severity)





        
        st.subheader("Top 3 Predictions")

        for skin_type, score in top3_predictions:
          st.write(f"• {skin_type.replace('_', ' ').title()} : {score*100:.2f}%")

        info = SKIN_INFO[predicted_class]

        st.subheader("About this Condition")

        st.write(info["description"])

        st.subheader("Recommended Skin Care")

        for tip in info["tips"]:
          st.write("✅", tip)

        st.warning(
    "This prediction is generated by an AI model and should not replace professional medical advice."
)

    else:
        st.warning("No face detected.")

# Run:
# streamlit run app.py


   
